### ISSUE TITLE
Why the capacitors between SSTX on the chip and SSRX on the connector?

### ISSUE THREAD

**Issue by taktoa** [danielkucera/cyusb3014-breakout#2]
As the title asks, why did you add 0.1uF capacitors between SSTX on the chip and SSRX on the connector? Also, why did you swap SSTX+ and SSTX-? Was this just to make the routing easier? Does it have any impact on maximum data rate?

**Comment by danielkucera** [comment]
Hi @taktoa , I was making changes strictly with accordance to with the [Hardware Design Guidelines](https://www.cypress.com/file/139936/download) , section 12.1
Capacitors are a must for this chip. 
You can swap + and - in USB3 differential pairs if it makes your routing easier.

**Comment by taktoa** [comment]
Thanks, that helps
